version: "3"

services:
    db:
        image: percona/percona-server
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_PASSWORD: dsw
            MYSQL_USER: dsw
            MYSQL_DATABASE: okiDSW
        container_name: oki-dsw
        volumes:
            - ./mysql:/var/lib/mysql
