### Obtener todos los juegos

GET http://localhost:3000/api/games


### Crear un nuevo game

# @name createGame
POST http://localhost:3000/api/games
Content-Type: application/json

{
  "id": 1,
  "name": "Mortaru Kombattu",
  "description": "A game that is considered by many to be the best fighting game ever made.",
  "imgUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9b8i.webp",
  "igdbId": 314153,
  "gametype": 2,
  "tags": [1]
}


### ID
@id = {{createGame.response.body.data.id}}


### Obtener un solo game usando un id

GET http://localhost:3000/api/games/{{id}}

### Modificar un game (PUT - Modificar recurso completo e idempotente)

PUT http://localhost:3000/api/games/{{id}}
Content-Type: application/json

{
  "id": 1,
  "name": "Mortaru Kombattu",
  "imgUrl": "https://images.igdb.com/igdb/image/upload/t_cover_big/co9b8i.webp",
  "igdbId": 314153,
  "gametype": 2,
  "tags": [1]
}
### Modificar un game (PATCH - Modificar recurso parcial)

PATCH http://localhost:3000/api/games/{{id}}
Content-Type: application/json

{
  "name": "Melty Blood",
  "description": "A niche fighting game that has impressive mechanics and a dedicated fanbase."
}


### Borrar un game (DELETE)

DELETE http://localhost:3000/api/games/{{id}}