### Obtener todas las inscripciones

GET http://localhost:3000/api/matchups


### Crear un nuevo inscripcion

# @name createMatchup
POST http://localhost:3000/api/matchups
Content-Type: application/json

{
    "player1Rounds":1,
    "player2Rounds":1,
    "status": "In Progress",
    "bracket": "",
    "round": 1,
    "player1Inscription": 1,
    "player2Inscription": 2,
    "winnerInscription": null,
    "tournament": 1,
    "winnerNextMatchup": 2,
    "losersNextMatchup": 3
}


### ID
@id = {{createMatchup.response.body.data.id}}


### Obtener una sola inscripcion usando un id

GET http://localhost:3000/api/matchups/{{id}}

### Modificar una inscripcion (PUT - Modificar recurso completo e idempotente)

PUT http://localhost:3000/api/matchups/{{id}}
Content-Type: application/json

{
    "player1Rounds":0,
    "player2Rounds":0,
    "status": "Done",
    "bracket": "",
    "round": "3",
    "player1Inscription": 1,
    "player2Inscription": 2,
    "winnerInscription": 1,
    "tournament": 1,
    "winnerNextMatchup": 2,
    "losersNextMatchup": 3
}




### Modificar una inscripcion (PATCH - Modificar recurso parcial)

PATCH http://localhost:3000/api/matchups/{{id}}
Content-Type: application/json

{
    "status": "Done",
    "round": "3",
    "winnerInscription": 1,
}


### Borrar una inscripcion (DELETE)

DELETE http://localhost:3000/api/matchups/{{id}}