### Obtener todos los tipos de juego

GET http://localhost:3000/api/game-types


### Crear un nuevo tipo de juego

# @name createGameType
POST http://localhost:3000/api/game-types
Content-Type: application/json

{
  "name": "Tag Fighter",
  "description": "Subgenre of fighting games where players control a team of characters, typically in pairs, and can switch between them during gameplay.",
  "tags":[1]
}


### ID
@id = {{createGameType.response.body.data.id}}


### Obtener un solo tipo de juego con un id

GET http://localhost:3000/api/game-types/{{id}}

# TODO: Decide if we want to use PUT or PATCH

### Modificar un tipo de juego (PUT - Modificar recurso completo e idempotente)

PUT http://localhost:3000/api/game-types/{{id}}
Content-Type: application/json

{
  "name": "Classic Fighter",
  "description": "Che en esto esta RYU.",
  "tags": ["SUPER STREET FIGHTER"]
}


### Modificar un tipo de juego (PATCH - Modificar recurso parcial)

PATCH http://localhost:3000/api/game-types/{{id}}
Content-Type: application/json

{
  "name": "CLASSICU FAITA",
  "tags": ["SUPER STREET FIGHTER", "KINU FAITA"]
}


### Borrar un tipo de juego (DELETE)

DELETE http://localhost:3000/api/game-types/{{id}}