### Obtener todos los torneos

GET http://localhost:3000/api/tournaments


### Crear un nuevo torneo

# @name createTournament
POST http://localhost:3000/api/tournaments
Content-Type: application/json

{
  "name": "Parry Palace 1st Tournament",
  "description": "The first tournament of the Parry Palace group",
  "datetimeinit": "2026-03-06T18:22:49.062Z",
  "status": "In progress",
  "maxParticipants": 32,
  "creator": 1,
  "game": 1,
  "inscriptions": []
}


### ID
@id = {{createTournament.response.body.data.id}}


### Obtener un solo torneo usando un id

GET http://localhost:3000/api/tournaments/{{id}}

### Modificar un torneo (PUT - Modificar recurso completo e idempotente)

PUT http://localhost:3000/api/tournaments/{{id}}
Content-Type: application/json

{
  "name": "Parry Palace 2nd Tournament",
  "description": "The second tournament of the Parry Palace group.",
  "datetimeinit": "2024-10-01T00:00:00.000Z",
  "status": "Done",
  "maxParticipants": 32,
  "creator": 1,
  "game": 1,
  "inscriptions": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
}


### Modificar un torneo (PATCH - Modificar recurso parcial)

PATCH http://localhost:3000/api/tournaments/{{id}}
Content-Type: application/json

{
  "name": "Parry Palace 3rd Tournament",
  "description": "The third tournament of the Parry Palace group.",
}


### Borrar un torneo (DELETE)

DELETE http://localhost:3000/api/tournaments/{{id}}